name: Open Issue when Netbox releases a new version
on:
  schedule:
    - cron: 45 * * * *

jobs:
  create_issue:
    name: Create team sync issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create team sync issue
        run: |
          previous_issue_date=$(gh issue list \
            --json createdAt \
            -s all \
            -S '[Chore]: Upgrade Netbox to' \
            -L 1 \
            --jq '.[0].createdAt')
          previous_issue_time=$(date -d previous_issue_date +%s)
          new_release=$(gh release list -R netbox-community/netbox \
            --exclude-drafts \
            --exclude-pre-releases \
            --json publishedAt,tagName \
            --jq '.[0]')
          new_release_tag=$(echo $new_release | jq '.tagName')
          new_release_date=$(echo $new_release | jq '.publishedAt')
          new_release_time=$(date -d new_release_date +%s)
          if [ $issue -ge $release ]; then
            gh issue create \
              --title "[Chore]: Upgrade netbox to $new_release_tag" \
              --body "$(gh release view $new_release_tag --repo netbox-community/netbox)"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
